# VERSION = {major}.{minor}.{datetime}
VERSION = "1.5.422-cuttingedge"

TWITCH_APP_ID = ""
TWITCH_APP_SECRET = ""

BILI_SESSDATA = ""
BILI_JCT = ""
BILI_DEDEUSERID = ""
BILI_DEDEUSERID_CKMD5 = ""
BILI_ACCESS_TOKEN = ""
